


accessibility
accessories
apps
cash
pay
backup
migrate
update
restore
bluetooth
wifi
buttons_and_switches
camera
flash
celular
phone
customer_sensory_issues
display
face_id
touch_id
features
settings
loaner_processing
physical_damage
power
safety
sensors
sound
system_wide_issues
third_party_apps
vibration
haptics


accessibility


hearing

physical
motor
vision

accessories

3rd-party_accessory
apple_headset/headphones
apple_iphone_case
apple_lighting_accessories
apple_power_adapter
euro_power_adapter

apple_apps

activity
airport_utility
app_store
apple_research_app
apple_watch
books
calculator
calender
clock
compass
contacts
facetime
files
find_my
health
home
icloud_drive
itunes_movie_trailers
itunes_store
itunes_u
mail
maps
measure
messages
music
news
notes
podcasts
reminders
safari
stocks
support_app
tips
videos/tv
voice_memos
wallet/passbook
weather

apple_cash

add_money_to_apple_cash_balance
apple_cash_rewards
apple_cash_transaction
disputes_or_unauthorized_charges
managed_apple_cash_account
restricted_or_locked_account
send/receive/request_apple_cash
transfer_to_bank_free
transfer_to_bank_instant
unusual_activity
verify_identity

apple_pay

apple_card_issues_us_only
apple_pay_disabled
credit/debit/prepaid_card_issues
lost_device_suspended_cards
student_id_card_issues_us_only
suspicious_activity
transit_card_issues

backup/migrate/update/restore

backup_device
erase_all_content_and_settings
ios_sw_update_/_ios_sw_restore
iphone_migration
migrate_from_andriod
restore_backup

bluetooth/wifi

bluetooth
accessory
car_radio
carplay
bluetooth_car_kit
wifi
troubleshoot
greyed_out
service

buttons_and_switches

home_button
side_/_sleep-wake_button
switch_-_ringer/silent
volume_buttons

camera/flash

camera_app_only
camera_front
camera_rear
led_flash_HT203040

celular/phone

activation/sim_not_supported
billing_and_account
call_forwarding/caller_id
calls_audio_quality
calls_calls_on_other_devices
calls_dropped/failed_call
calls_making_calls
calls_receiving_calls
calls_VoLTE
calls_wifi_calling
cellular_update_failed_alert
emergency_call/text/SOS
international/roaming
invalid_sim
ios_instant_hotspot
no_service/searching
no_sim_
personal_hotspot
ringer_vibration
signal_strength_poor
unlocking
voicemail

customer_sensory_issues

temperature_perception:_AC_Adapter
temperature_perception:_unit
unexpected_alert_noise
unexpected_noise_not_an_alert

display

threed_touch/haptic_touch
blank_black_screen-power_on
blank_white_screen-power_on
brightness/backlight_issues
calibration_unsuccessful
display_loose
display_produces_clicking_noise
flickering_/_flashing
image_quality
issue_persists_after_repair
lines/blocks/bands
multi-touch
pixels_/_foreign_material

face_id_/_touch_id

unable_to_set_up_face_id_/_touch_id
unlock-authenticate_face_id_/touch_id

features/settings

airdrop
airplane_mode
airplay
airprint
app_handoff
carplay
control_center
dark_mode
date_and_time
home_screen/_lock_screen
internation/region_format
keyboard
multitasking_/_drag&drop
night_shift
notifications/do_not_disturb
passcode_lock/auto-lock
privacy/location_services
screen_time/restrictions
search
siri/siri_shortcuts
TV_provider_sign_in

loaner_processing

no_trouble_found

physical_damage

button/switch_damage
camera_lens_damage
counterfeit_device_suspected
diagnostic_fee
display_multiple_cracks
display_single_crack
dock_connector_on_device
enclosure_bent
enclosure_bubbling
dent/scratch
discoloration
enterprise_entitled_replacement
iUP_display_non_repair_china
liquid_damage
lost_iphone_reported_
physical_damage_during_repair
rear_glass_multiple_cracks
rear_glass_single_crack
sim_tray
speaker/mic/receiver_damage
swollen_battery

power_

battery_life/performace
diagnostics_say_ac_wall_plug
diagnostics_say_main_logic_board
will_not_power_on/wired_charging
wireless_charging_issues

safety

fire
leakage
sharp_edges
skin_irritation
smoke_
spark_/_shock
unusual_heat
unusual_smell
_
sensors

accelerometer/gyro/barometer
ambient_light_sensor_als
proximity_sensor
true_tone

no_sound_||_sound_quality

headset_connector
receiver
mic
speaker
other_system_sounds

system-wide_issues
capacity/low_disk_space
device_not_seen_in_computer
device_running_slowly
power_on_-_device_unresponsive
temperature_/_accessory_alert
unexpected_restart_/_shutdown

third_party_apps

launch_/_locate_app
pop-ups_redirects_phishing
spam_phone_call_/_sms_blocking

vibration/haptics

no_vibration/_no_haptic_(taptic)
weak_vibration/_weak_haptic_(taptic)
